/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator */

#ifndef _Included_Calculator
#define _Included_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculator_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculator
 * Method:    sub
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculator_sub
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculator
 * Method:    mul
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculator_mul
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculator
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculator_div
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
